import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useCallback, useEffect } from "react";
import Experiences from "../components/Experiences";
import Getaways from "../components/Getaways";
import Header from "../components/Header";
import HeaderScroll from "../components/HeaderScroll";
import TripInspiration from "../components/TripInspiration";
import { useHeaderContext } from "../Context/HeaderContext";

const Home: NextPage = () => {
  const {
    scrollPosition,
    startSearchOpen,
    setScrollPosition,
    setStartSearchOpen,
  } = useHeaderContext();

  const handleScroll = useCallback(() => {
    const position = window.scrollY;
    setScrollPosition(position);
    setStartSearchOpen(false);
  }, [setScrollPosition, setStartSearchOpen]);

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);

    return () => window.removeEventListener("scroll", handleScroll);
  }, [handleScroll]);

  const startSearchClick = async (): Promise<void> => {
    await window.removeEventListener("scroll", handleScroll);
    setStartSearchOpen(true);
    setTimeout(() => {
      return () => window.addEventListener("scroll", handleScroll);
    }, 500);
  };

  return (
    <div>
      <Head>
        <title>Airbnb</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {scrollPosition === 0 || startSearchOpen ? (
        <Header />
      ) : (
        <HeaderScroll startSearchClick={startSearchClick} />
      )}

      <section className='flex bg-black w-full h-screen md:h-[600px] xl:h-[880px]'>
        <div className='bg-bgTopMobile md:bg-bgTopDesktop bg-no-repeat w-full bg-center md:mx-auto bg-cover lg:h-[600px] xl:h-[800px] xl:w-5/6 p-6 flex flex-col items-center justify-end xl:rounded-3xl'>
          <div className='flex flex-col items-center justify-center mb-10'>
            <h1 className='text-3xl md:text-5xl font-semibold text-center text-white mt-20 mb-8'>
              Not sure where to go?
              <br className='md:hidden' />
              <span> Perfect.</span>
            </h1>
            <div className='bg-white hover:bg-gray-50 w-36 rounded-full'>
              <button className='bg-gradient-to-tr from-[#6F019C] to-[#C6017E] text-transparent bg-clip-text w-full py-3 rounded-full text-lg font-semibold'>
                I&apos;m flexible
              </button>
            </div>
          </div>
        </div>
      </section>
      <section className='bg-white h-[800px] w-full overflow-hidden'>
        <div className="flex flex-col w-5/6 mx-auto my-20">
          <div className="flex items-center">
            <h2 className='text-[1.6rem] md:text-[2.6rem] font-semibold mb-10'>Inspiration for your next trip</h2>
            <div className="flex gap-2 h-[100px] md:hidden">
              <div className="flex justify-center items-center w-8 h-8 border-2 rounded-full text-xl font-semibold">{'<'}</div>
              <div className="flex justify-center items-center w-8 h-8 border-2 rounded-full text-xl font-semibold">{'>'}</div>
            </div>
          </div>
          <TripInspiration />
        </div>
      </section>

      <section className="bg-white h-[1000px]">
        <div className="md:w-5/6 mx-auto">
          <h2 className="text-4xl font-semibold mb-16">Discover Airbnb Experiences</h2>
          <div className="flex gap-8">
            <Experiences img='/images/experiences.webp' heading='Things to do on your trip' btnText='Experiences' />
            <Experiences img='/images/online-experiences.webp' heading='Things to do from home' btnText='Online Experiences' />
          </div>
        </div>
      </section>

      <section className="bg-white h-[500px]">
        <div className="flex justify-between w-5/6 mx-auto">
          <div className="w-[300px]">
            <h2 className="text-5xl font-semibold mb-10">Shop Airbnb gift cards</h2>
            <button className="w-36 h-12 rounded-2xl bg-gray-900 hover:bg-black text-white">Learn More</button>
          </div>
          <div className="relative w-[1000px] h-[400px]">
            <Image src='/images/gift-cards.webp' layout="fill" alt='' />
          </div>
        </div>
      </section>

      <section className="bg-white w-f h-[900px]">
        <div className="relative w-5/6 h-[800px] mx-auto rounded-3xl">
          <Image src='/images/ask-a-superhost.jpg' layout='fill' className='rounded-3xl object-contain' alt='' />
          <div className="absolute flex flex-col justify-between p-14 top-0 left-0 w-full h-full text-white rounded-3xl">
            <h3 className="text-7xl font-bold w-[300px]">Questions about hosting?</h3>
            <button className="w-36 h-14 bg-white hover:bg-gray-100 text-black rounded-2xl">Ask a Superhost</button>
          </div>
        </div>
      </section>

      <section className="bg-white w-full h-[500px]">
        <div className="w-5/6 mx-auto">
          <h2 className="text-2xl font-medium mb-2 ml-2">Inspiration for future getaways</h2>
          <Getaways />
        </div>
      </section>

      <footer className="bg-gray-200 w-full h-[400px]">
        <div className="flex w-5/6 mx-auto">
          <div className="flex flex-col flex-grow">
            <p>Support</p>
            <a>Help Center</a>
            <a>Safety information</a>
            <a>Cancellation options</a>
            <a>Our COVID-19 Response</a>
            <a>Supporting people with disabilities</a>
            <a>Report a neighborhood concern</a>
          </div>
          <div className="flex flex-col flex-grow">
            <p>Community</p>
            <a>Airbnb.org: disaster relief housing</a>
            <a>Support Afghan refugees</a>
            <a>Combating discrimination</a>
          </div>
          <div className="flex flex-col flex-grow">
            <p>Hosting</p>
            <a>Try hosting</a>
            <a>AirCover: protection for Hosts</a>
            <a>Explore hosting resources</a>
            <a>Visit our community forum</a>
            <a>How to host responsibly</a>
          </div>
          <div className="flex flex-col flex-grow">
            <p>About</p>
            <a>Newsroom</a>
            <a>Learn about new features</a>
            <a>Letter from our founders</a>
            <a>Careers</a>
            <a>Investors</a>
            <a>Airbnb Luxe</a>
          </div>
        </div>
        <hr />
        <div className="flex w-5/6 mx-auto justify-between mt-10">
          <div className="flex">
            <p>© Airbnb Inc.</p>
            <p>Privacy</p>
            <p>Terms</p>
            <p>Site map</p>
          </div>
          <div className="flex">
            <p>English(US)</p>
            <p>$ USD</p>
            <div className="flex">
              <p>f</p>
              <p>t</p>
              <p>i</p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Home;
