import type { NextPage } from "next";
import Head from "next/head";
import { useCallback, useEffect } from "react";
import Header from "../components/Header";
import HeaderScroll from "../components/HeaderScroll";
import TripInspiration from "../components/TripInspiration";
import { useHeaderContext } from "../Context/HeaderContext";

const Home: NextPage = () => {
  const {
    scrollPosition,
    startSearchOpen,
    setScrollPosition,
    setStartSearchOpen,
  } = useHeaderContext();

  const handleScroll = useCallback(() => {
    const position = window.scrollY;
    setScrollPosition(position);
    setStartSearchOpen(false);
  }, [setScrollPosition, setStartSearchOpen]);

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);

    return () => window.removeEventListener("scroll", handleScroll);
  }, [handleScroll]);

  const startSearchClick = async (): Promise<void> => {
    await window.removeEventListener("scroll", handleScroll);
    setStartSearchOpen(true);
    setTimeout(() => {
      return () => window.addEventListener("scroll", handleScroll);
    }, 500);
  };

  return (
    <div>
      <Head>
        <title>Airbnb</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {scrollPosition === 0 || startSearchOpen ? (
        <Header />
      ) : (
        <HeaderScroll startSearchClick={startSearchClick} />
      )}

      <section className='flex bg-black w-full h-screen md:h-[600px] xl:h-[880px]'>
        <div className='bg-bgTopMobile md:bg-bgTopDesktop bg-no-repeat w-full bg-center md:mx-auto bg-cover lg:h-[600px] xl:h-[800px] xl:w-5/6 p-6 flex flex-col items-center justify-end xl:rounded-3xl'>
          <div className='flex flex-col items-center justify-center mb-10'>
            <h1 className='text-3xl md:text-5xl font-semibold text-center text-white mt-20 mb-8'>
              Not sure where to go?
              <br className='md:hidden' />
              <span> Perfect.</span>
            </h1>
            <div className='bg-white hover:bg-gray-50 w-36 rounded-full'>
              <button className='bg-gradient-to-tr from-[#6F019C] to-[#C6017E] text-transparent bg-clip-text w-full py-3 rounded-full text-lg font-semibold'>
                I&apos;m flexible
              </button>
            </div>
          </div>
        </div>
      </section>
      <section className='bg-white h-[800px] w-full overflow-hidden'>
        <div className="flex flex-col w-5/6 mx-auto my-20">
          <div className="flex items-center">
            <h2 className='text-[1.6rem] md:text-[2.6rem] font-semibold mb-10'>Inspiration for your next trip</h2>
            <div className="flex gap-2 h-[100px] md:hidden">
              <div className="flex justify-center items-center w-8 h-8 border-2 rounded-full text-xl font-semibold">{'<'}</div>
              <div className="flex justify-center items-center w-8 h-8 border-2 rounded-full text-xl font-semibold">{'>'}</div>
            </div>
          </div>
          <TripInspiration />
        </div>
      </section>
    </div>
  );
};

export default Home;
